"""create users2

Revision ID: 3ea3814cf0ad
Revises: ba3b947ee624
Create Date: 2024-06-27 21:53:58.837006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ea3814cf0ad'
down_revision = 'ba3b947ee624'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users2', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users2', schema=None) as batch_op:
        batch_op.drop_column('username')

    # ### end Alembic commands ###
