"""Add Arena to Teams.

Revision ID: 7a6bb796d97d
Revises: cf910d77a549
Create Date: 2024-06-22 11:35:34.969070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a6bb796d97d'
down_revision = 'cf910d77a549'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('arena', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_column('arena')

    # ### end Alembic commands ###
