"""Add Timestamp to Teams

Revision ID: ba3b947ee624
Revises: ab07d972551f
Create Date: 2024-06-26 20:47:45.939964

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime, timedelta


# revision identifiers, used by Alembic.
revision = 'ba3b947ee624'
down_revision = 'ab07d972551f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.execute(f"UPDATE teams SET created_at = '{datetime.utcnow() + timedelta(hours=7)}', updated_at = '{datetime.utcnow() + timedelta(hours=7)}'")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teams', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
